apiVersion: v1
kind: Pod
metadata:
  name: vault-test-pod
  labels:
    app: vault-test-pod
  annotations:
    vault.hashicorp.com/agent-inject: 'true'

    vault.hashicorp.com/role: 'kubernetes-role'

    vault.hashicorp.com/agent-inject-secret-info.txt: 'kv-secret/info'

    vault.hashicorp.com/agent-inject-template-info.txt: |
      {{- with secret "kv-secret/info" -}}
      SECRET_KEY: {{ .Data.data.SECRET_KEY }}
      {{- end -}}
spec:
  containers:
  - name: app
    image: ubuntu:22.04
    command: ["/bin/sh", "-c", "while :; do sleep 10; done"]
  serviceAccountName: app
